### ISSUE TITLE
Removing a DC spike should be optional (main.cu)

### ISSUE THREAD

**Issue by texadactyl** [lacker/seticore#1]
Some telescope arrays, have no DC spike.  According to David McMahon, the spike comes about because of a shortcut taken in the FPGA design of the coarse channelizer (aka "F engine").

So, this should be a flag-driven feature.

**Comment by lacker** [comment]
That makes sense. Maybe it should even just make the correct decision based on the h5 file - one of the headers has the information about which telescope it is, right? Then we wouldn't have to ask people to get a bunch of flags right all the time.

**Comment by texadactyl** [comment]
DC spikes might be just Parkes and GBT.  LOFAR?  Need verification on all of them.

**Comment by lacker** [comment]
Wael says the ATA does not have a DC spike

**Comment by texadactyl** [comment]
Makes sense. Danny said it was mostly a characteristic of single-antenna telescopes.  Base it on telescope ID?

**Comment by lacker** [comment]
I'll make it part of the telescope-guessing logic, since I still see plenty of data with telescope id -1...

**Comment by lacker** [comment]
Meerkat data also has no DC spike. Mentioning here for later reference

**Comment by lacker** [comment]
DC spike is now part of the telescope-guessing logic:

https://github.com/lacker/seticore/commit/987cc9c0f452200811a36aa5d1ec1a558a266aa1
