### ISSUE TITLE
Provide version on every execution --> stdout

### ISSUE THREAD

**Issue by texadactyl** [lacker/seticore#10]
Folks will be capturning seticore stdout in a log file in case something goes wrong or their ssh session times out.  I suggest that you add a display of the program version (cheap):

 ```cout << "seticore version: " << VERSION << endl;```

**Comment by lacker** [comment]
yes... it might also be nice to include a git hash, I'll look into how straightforward that would be to set up

**Comment by lacker** [comment]
git hash is a little too much work, i'm going to punt on that until such time as someone wants it, I did make the version show up all the time, as well as printing out all params passed to dedoppler, as of version 0.0.2

https://github.com/lacker/seticore/commit/ca29e6283031a668fc0e1011f990d1c95432b98e
