### ISSUE TITLE
Exception when running with a lower SNR value (MeerKAT)

### ISSUE THREAD

**Issue by danielczech** [lacker/seticore#14]
When running `seticore` on `blpn35` using the following slurm command (constructed by [blproc_manual](https://github.com/danielczech/commensal-automator/blob/main/automator/blproc_manual.py)) from the BLUSE headnode:  

`'srun', '-w', 'blpn35', '/home/lacker/seticore/build/seticore', '--input=/buf0ro/20220512/0009/Unknown/GUPPI', '--output=/scratch/test.20220713', '--max_drift=10', '--snr=6', '--recipe_dir=/home/davidm/bfr5.test', '--num_bands=16', '--fft_size=131072', '--telescope_id=64'`  

an error is encountered (see below). Note SNR is set to be 6 here instead of 10 given in the [example](https://github.com/lacker/seticore/blob/master/test_meerkat_pong.sh).   

Speculation: could it be that seticore just doesn't have write permissions for `/scratch/test.20220713'`?  

The `blproc_manual` command used is as follows: 
`blproc_manual --proc_type slurm --outdir /scratch/test.20220713 --inputdir /buf0ro/20220512/0009/Unknown/GUPPI --hosts blpn35
`

Seticore output:  
```
welcome to seticore, version 0.1.0
running in beamforming mode.
found 8 groups of raw files.
recording hits to /scratch/test.20220713/guppi_59712_16307_003760_J1939-6342_0001.hits
drift rate resolution: 0.0453962

beamforming band 0 run 0...
beamforming band 0 run 1...
beamforming band 0 run 2...
beamforming band 0 run 3...
beamforming band 0 run 4...

band 0: dedoppler searching 524288 channels, 5 timesteps
recorded 0 hits

beamforming band 1 run 0...
beamforming band 1 run 1...
beamforming band 1 run 2...
beamforming band 1 run 3...
beamforming band 1 run 4...

band 1: dedoppler searching 524288 channels, 5 timesteps
recorded 0 hits

beamforming band 2 run 0...
beamforming band 2 run 1...
beamforming band 2 run 2...
beamforming band 2 run 3...
beamforming band 2 run 4...

band 2: dedoppler searching 524288 channels, 5 timesteps
recorded 0 hits

beamforming band 3 run 0...
beamforming band 3 run 1...
beamforming band 3 run 2...
beamforming band 3 run 3...
beamforming band 3 run 4...

band 3: dedoppler searching 524288 channels, 5 timesteps
recorded 0 hits

beamforming band 4 run 0...
beamforming band 4 run 1...
beamforming band 4 run 2...
beamforming band 4 run 3...
beamforming band 4 run 4...

band 4: dedoppler searching 524288 channels, 5 timesteps
  index = 53077, drift steps = 128, snr = 6.28664, drift rate = 5.81072
terminate called after throwing an instance of 'kj::ExceptionImpl'
  what():  kj/io.c++:405: failed: ::writev(fd, current, iov.end() - current): Bad file descriptor; fd = -1
stack: 4a1b60 47c79e 47c990 41a305 4118e4 40e13f 7f428e81a82f 40ea08
srun: error: blpn35: task 0: Aborted
```

**Comment by lacker** [comment]
That directory is only writeable by root. I don't know what user you are running slurm as, but (hopefully) not root.

```
lacker@blpn35:~$ ls -la /scratch/
total 4
drwxr-xr-x  4 root root   55 Jul 13 14:27 .
drwxr-xr-x 32 root root 4096 Feb  8  2021 ..
drwxr-xr-x  3 root root   18 Dec  9  2020 20201203
drwxr-xr-x  2 root root    6 Jul 13 14:27 test.20220713
```

It would be nice if seticore exited with a clean error saying "this process lacks permissions to write to the directory /scratch/blah/blah" rather than dying with some incomprehensible kj/io.c++ error

**Comment by lacker** [comment]
Yeah, I was just sloppily ignoring errors in some filesystem api call. version 0.1.2 is now deployed to meerkat, which makes this error message tell you when the file can't be opened.
