### ISSUE TITLE
Amend README concerning ninja installation

### ISSUE THREAD

**Issue by texadactyl** [lacker/seticore#15]
Users may not be able to install ninja via `apt` because they do not have admin/root access.  This is an effective alternative:

```python3 -m pip install --user -U ninja```

Also, all references to ```pip``` should be amended to use pip as a module: ```python3 -m pip .....```

**Comment by lacker** [comment]
I agree; fixed in https://github.com/lacker/seticore/commit/fba21abe47c01ceabc8ae7bf6538a1714f7c19d3
