### ISSUE TITLE
HitsGroups could have overlapping frequency spans

### ISSUE THREAD

**Issue by radonnachie** [lacker/seticore#30]
Looking at how groups are created (and as concluded in a slack thread) HitsGroups could be improved so that it isn't possible for the frequency-span of groups to overlap.

Currently it is possible because only the last group in the vector of groups is considered when placing a hit, and a group's boundaries expand to express the extremes of its hits. So the following is possible:
- The first hit is placed in a group
- The second hit is placed in its own group because it does not overlap with the first
- Subsequent hits are placed in the second group because they overlap with the group, but ultimately this group expands to overlap with the range of the first

Changing the algorithm to consider all groups, selecting the first overlapping one isn't foolproof because it could just expand the first group to overlap with a subsequent group. 

The algorithm could be foolproof if it considers all groups and merges all candidate groups: the hit overlaps boundaries between these groups causing them to form 1.

Alternatively one could double-check the groups before returning them... but that seems less efficient.
<details><summary>It's unfortunately what I wrote some code for</summary>
```
for (size_t group_a = 0; group_a < groups.size(); group_a++) {
        size_t group_b = group_a + 1;
        while (group_b < groups.size()) {
            if (groups[group_b].low_index >= groups[group_a].high_index) {
                // group_b starts after group_a
                group_b += 1;
                continue;
            }
            if (groups[group_b].high_index <= groups[group_a].low_index) {
                // group_b ends before group_a
                group_b += 1;
                continue;
            }
            // group_b overlaps with group_a
            groups[group_a].hits.insert(
                groups[group_a].hits.end(),
                groups[group_b].hits.begin(),
                groups[group_b].hits.end()
            );
            groups[group_b].clear();
            groups.erase(groups.begin()+group_b);
            sort(groups[group_a].hits.begin(), groups[group_a].hits.end());
            group_b = group_a + 1;
        }
    }
```
</details>

If the merging of multiple candidate groups by a hit is something you're interested in I'm happy to write up the PR.

**Comment by lacker** [comment]
I think this is only a problem in the deduplication that happens on the GPU. Then it isn't so straightforward to change how we deduplicate.

For the CPU deduplication, I think we avoid this, because when we go through hits we first sort them:

https://github.com/lacker/seticore/blob/master/dedoppler_hit_group.cpp#L43

and sorting will go by the lowest index:

https://github.com/lacker/seticore/blob/master/dedoppler_hit.cpp#L57

which should mean that subsequent hits can never lower the lowest index of a group, because all subsequent hits have a higher lowest index than previous hits.

**Comment by radonnachie** [comment]
Righto! sorting the hits before grouping them mitigates this. Thanks for highlights
