### ISSUE TITLE
Add a GPU ID command line parameter (main.cpp)

### ISSUE THREAD

**Issue by texadactyl** [lacker/seticore#6]
dedoppler should be passed a GPU ID parameter for use with cudaSetDevice(gpu_id)
Command line default: 0

**Comment by lacker** [comment]
Is it good enough to use the environment variable `CUDA_VISIBLE_DEVICES` ? I'd rather not support extra flags if there's already some way to do it.

**Comment by texadactyl** [comment]
rawspec, turbo_seti, and hyperseti have set a precedent by providing this flexibility

**Comment by texadactyl** [comment]
Should seticore become successful, this won't be the last user interface change

**Comment by texadactyl** [comment]
e.g. min_drift_rate which might be set quite high in the case of Mars

**Comment by texadactyl** [comment]
The author has the right to design how a specific device is selected. Therefore, I am closing this issue and opening a PR that just amends README.md to add a section on how to deterministically select a specific device using environment variables.
