### ISSUE TITLE
Enhancement request: Add a version to seticore

### ISSUE THREAD

**Issue by texadactyl** [lacker/seticore#8]
Maintain the version in version.h which is included by main.cpp.
Announce the version when execution begins.

#define VERSION 1.0.0

Extra credit: 
* Add an -h parameter which does the same thing as starting seticore without parameters does. Reasoning: The scientists are used to using -h with their tools when they forget the command line usage.
* Get Matt to put the seticore executable in /usr/local/bin, visible to all 3 compute nodes.  It's time for others to kick the tires.

**Comment by lacker** [comment]
I added a version and a -h / --help flag. I'll put the executable in /usr/local/bin Real Soon Now
